# Configure this Discovery Server
eureka:
  instance:
    hostname: discoveryServer
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

# HTTP Server
server:
  port: 8080
  servlet:
      context-path: /discovery-server


  #http://localhost:8080/discovery-server/